<Project>
  <PropertyGroup>
    <LangVersion>12</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsNotAsErrors>CS1591</WarningsNotAsErrors>
    <Deterministic>true</Deterministic>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <ImplicitUsings>disable</ImplicitUsings>
    <DebugType>portable</DebugType>
    <DotNetCliToolTelemetryOptOut>true</DotNetCliToolTelemetryOptOut>
  </PropertyGroup>
</Project>
