using System;
using Brinehold.Core.Collections;
using Brinehold.Core.Math;
using Brinehold.Sim.World;

namespace Brinehold.Sim.Content
{
    /// <summary>
    /// Every tunable value the simulation reads, in one place, as data rather than as code.
    ///
    /// It is an instance rather than a static table so that a match can be started with a different
    /// balance pass — loaded from JSON, generated by a test, or shipped as a tournament ruleset —
    /// without touching the systems that consume it. The systems read <c>world.Content</c>; nothing
    /// in the simulation hard-codes a cost or a rate.
    ///
    /// The database hashes itself, and that hash is part of the handshake. A client that edits its
    /// content files to make its own units cheaper cannot join a match, because the server will not
    /// recognise its build.
    /// </summary>
    public sealed class ContentDatabase
    {
        public struct UnitStats
        {
            public Fix64 MaxHealth;
            public Fix64 MoveSpeed;        // metres per second
            public Fix64 VisionRange;      // metres
            public Fix64 AttackDamage;
            public Fix64 AttackRange;      // metres
            public int AttackCooldownTicks;
            public int CarryCapacity;
            public int TrainTicks;
            public int PopulationCost;
            public int CostWood;
            public int CostFood;
            public int CostStone;
            public int CostCoin;
            public MovementDomain Domain;
        }

        public struct BuildingStats
        {
            public Fix64 MaxHealth;
            public Fix64 VisionRange;
            public int FootprintHalf;
            public int BuildTicks;
            public int CostWood;
            public int CostFood;
            public int CostStone;
            public int CostCoin;
            public bool RequiresWaterAdjacency;
            public bool IsDropOff;
            public int PopulationCapacity;
            /// <summary>Unit kinds this building may train, as a bit mask over <see cref="EntityKind"/>.</summary>
            public int TrainableMask;
        }

        public struct NodeStats
        {
            public int Capacity;
            public ResourceType Yields;
        }

        private const int UnitKinds = 8;
        private const int BuildingKinds = 8;
        private const int NodeKinds = 8;

        private readonly UnitStats[] _units = new UnitStats[UnitKinds];
        private readonly BuildingStats[] _buildings = new BuildingStats[BuildingKinds];
        private readonly NodeStats[] _nodes = new NodeStats[NodeKinds];

        // ---------------------------------------------------------------- tunables

        /// <summary>Ticks to extract one unit of a resource from a node.</summary>
        public int HarvestTicksPerUnit = 12;

        /// <summary>Build progress one worker contributes per tick.</summary>
        public int BuildProgressPerWorkerTick = 1;

        public int StartingWood = 200;
        public int StartingFood = 200;
        public int StartingStone = 100;
        public int StartingCoin = 100;
        public int StartingWorkers = 10;
        public int BasePopulationCap = 5;
        public int MaxPopulationCap = 50;

        /// <summary>Human-readable label, so a match log can say which ruleset it ran.</summary>
        public string Name = "prototype";

        // ---------------------------------------------------------------- lookups

        public UnitStats Unit(EntityKind kind)
        {
            int index = (int)kind;
            return index >= 0 && index < UnitKinds ? _units[index] : _units[(int)EntityKind.Worker];
        }

        public BuildingStats Building(BuildingType type)
        {
            int index = (int)type;
            return index >= 0 && index < BuildingKinds ? _buildings[index] : _buildings[0];
        }

        public NodeStats Node(ResourceNodeType type)
        {
            int index = (int)type;
            return index >= 0 && index < NodeKinds ? _nodes[index] : _nodes[0];
        }

        public bool CanTrain(BuildingType building, EntityKind kind)
            => (Building(building).TrainableMask & (1 << (int)kind)) != 0;

        public void SetUnit(EntityKind kind, UnitStats stats) => _units[(int)kind] = stats;
        public void SetBuilding(BuildingType type, BuildingStats stats) => _buildings[(int)type] = stats;
        public void SetNode(ResourceNodeType type, NodeStats stats) => _nodes[(int)type] = stats;

        public static int TrainMask(params EntityKind[] kinds)
        {
            int mask = 0;
            foreach (EntityKind kind in kinds) mask |= 1 << (int)kind;
            return mask;
        }

        // ---------------------------------------------------------------- integrity

        /// <summary>
        /// Fingerprints every value the simulation reads. Part of the handshake, so a client running
        /// edited content is refused rather than silently playing a different game.
        /// </summary>
        public ulong ContentHash()
        {
            var hash = StateHash.Create();
            hash.Add(HarvestTicksPerUnit);
            hash.Add(BuildProgressPerWorkerTick);
            hash.Add(StartingWood); hash.Add(StartingFood); hash.Add(StartingStone); hash.Add(StartingCoin);
            hash.Add(StartingWorkers); hash.Add(BasePopulationCap); hash.Add(MaxPopulationCap);

            for (int i = 0; i < UnitKinds; i++)
            {
                UnitStats u = _units[i];
                hash.Add(u.MaxHealth); hash.Add(u.MoveSpeed); hash.Add(u.VisionRange);
                hash.Add(u.AttackDamage); hash.Add(u.AttackRange); hash.Add(u.AttackCooldownTicks);
                hash.Add(u.CarryCapacity); hash.Add(u.TrainTicks); hash.Add(u.PopulationCost);
                hash.Add(u.CostWood); hash.Add(u.CostFood); hash.Add(u.CostStone); hash.Add(u.CostCoin);
                hash.Add((int)u.Domain);
            }

            for (int i = 0; i < BuildingKinds; i++)
            {
                BuildingStats b = _buildings[i];
                hash.Add(b.MaxHealth); hash.Add(b.VisionRange); hash.Add(b.FootprintHalf);
                hash.Add(b.BuildTicks); hash.Add(b.CostWood); hash.Add(b.CostFood);
                hash.Add(b.CostStone); hash.Add(b.CostCoin);
                hash.Add(b.RequiresWaterAdjacency); hash.Add(b.IsDropOff);
                hash.Add(b.PopulationCapacity); hash.Add(b.TrainableMask);
            }

            for (int i = 0; i < NodeKinds; i++)
            {
                hash.Add(_nodes[i].Capacity);
                hash.Add((int)_nodes[i].Yields);
            }

            return hash.Value;
        }

        /// <summary>
        /// Structural checks a balance pass must survive. Returns every problem found rather than the
        /// first, so a designer editing content sees the whole list at once.
        /// </summary>
        public string[] Validate()
        {
            var problems = new System.Collections.Generic.List<string>();

            foreach (EntityKind kind in new[] { EntityKind.Worker, EntityKind.Soldier, EntityKind.Ship })
            {
                UnitStats u = Unit(kind);
                if (u.MaxHealth <= Fix64.Zero) problems.Add($"{kind}: max health must be positive");
                if (u.MoveSpeed <= Fix64.Zero) problems.Add($"{kind}: move speed must be positive");
                if (u.TrainTicks <= 0) problems.Add($"{kind}: train time must be positive");
                if (u.PopulationCost <= 0) problems.Add($"{kind}: population cost must be positive");
                if (u.VisionRange <= Fix64.Zero) problems.Add($"{kind}: vision must be positive, or it can never see anything");
            }

            foreach (BuildingType type in new[]
                     {
                         BuildingType.Warehouse, BuildingType.House, BuildingType.LumberCamp,
                         BuildingType.FishingWharf, BuildingType.Dock
                     })
            {
                BuildingStats b = Building(type);
                if (b.MaxHealth <= Fix64.Zero) problems.Add($"{type}: max health must be positive");
                if (b.BuildTicks <= 0) problems.Add($"{type}: build time must be positive");
                if (b.FootprintHalf < 0) problems.Add($"{type}: footprint cannot be negative");
            }

            // Every resource a node yields must be one a player can actually store and spend.
            foreach (ResourceNodeType type in new[]
                     { ResourceNodeType.Forest, ResourceNodeType.FishShoal, ResourceNodeType.StoneOutcrop })
            {
                NodeStats n = Node(type);
                if (n.Capacity <= 0) problems.Add($"{type}: capacity must be positive");
                if ((int)n.Yields >= SimConstants.ResourceTypeCount)
                    problems.Add($"{type}: yields an unknown resource");
            }

            // A settlement that cannot train a worker cannot recover from losing them.
            bool anyTrainsWorkers = false;
            foreach (BuildingType type in new[]
                     {
                         BuildingType.Warehouse, BuildingType.House, BuildingType.LumberCamp,
                         BuildingType.FishingWharf, BuildingType.Dock
                     })
            {
                if (CanTrain(type, EntityKind.Worker)) anyTrainsWorkers = true;
            }
            if (!anyTrainsWorkers) problems.Add("no building can train a worker");

            // At least one building must accept deliveries, or nothing harvested can ever be banked.
            bool anyDropOff = false;
            for (int i = 0; i < BuildingKinds; i++) if (_buildings[i].IsDropOff) anyDropOff = true;
            if (!anyDropOff) problems.Add("no building accepts deliveries, so harvesting can never bank anything");

            // The opening must be affordable: a player who cannot afford their first house is stuck.
            if (Building(BuildingType.House).CostWood > StartingWood)
                problems.Add("a house costs more wood than a player starts with");

            return problems.ToArray();
        }

        // ---------------------------------------------------------------- the default ruleset

        /// <summary>
        /// The prototype's balance, as code. The JSON loader in `com.brinehold.content` produces the
        /// same structure; this stays as the fallback so the simulation is never unable to start.
        /// Design intent for every number is in ECONOMY_DESIGN.md and COMBAT_DESIGN.md.
        /// </summary>
        public static ContentDatabase CreateDefault()
        {
            var db = new ContentDatabase { Name = "prototype" };

            db.SetUnit(EntityKind.Worker, new UnitStats
            {
                MaxHealth = Fix64.FromInt(60),
                MoveSpeed = Fix64.FromFraction(14, 10),
                VisionRange = Fix64.FromInt(12),
                AttackDamage = Fix64.FromInt(3),
                AttackRange = Fix64.FromInt(1),
                AttackCooldownTicks = 30,
                CarryCapacity = 8,
                TrainTicks = 240,
                PopulationCost = 1,
                CostFood = 50,
                Domain = MovementDomain.Land
            });

            db.SetUnit(EntityKind.Soldier, new UnitStats
            {
                MaxHealth = Fix64.FromInt(60),
                MoveSpeed = Fix64.FromFraction(32, 10),
                VisionRange = Fix64.FromInt(14),
                AttackDamage = Fix64.FromInt(9),
                AttackRange = Fix64.FromFraction(15, 10),
                AttackCooldownTicks = 20,
                CarryCapacity = 0,
                TrainTicks = 240,
                PopulationCost = 1,
                CostFood = 35, CostCoin = 15,
                Domain = MovementDomain.Land
            });

            db.SetUnit(EntityKind.Ship, new UnitStats
            {
                MaxHealth = Fix64.FromInt(200),
                MoveSpeed = Fix64.FromInt(5),
                VisionRange = Fix64.FromInt(30),
                AttackDamage = Fix64.FromInt(20),
                AttackRange = Fix64.FromInt(20),
                AttackCooldownTicks = 160,
                CarryCapacity = 0,
                TrainTicks = 900,
                PopulationCost = 3,
                CostWood = 40, CostCoin = 40,
                Domain = MovementDomain.Water
            });

            db.SetBuilding(BuildingType.Warehouse, new BuildingStats
            {
                MaxHealth = Fix64.FromInt(800), VisionRange = Fix64.FromInt(20),
                FootprintHalf = 2, BuildTicks = 600,
                CostWood = 150, CostStone = 50,
                IsDropOff = true, PopulationCapacity = 5,
                TrainableMask = TrainMask(EntityKind.Worker, EntityKind.Soldier)
            });

            db.SetBuilding(BuildingType.House, new BuildingStats
            {
                MaxHealth = Fix64.FromInt(400), VisionRange = Fix64.FromInt(10),
                FootprintHalf = 1, BuildTicks = 300,
                CostWood = 50, PopulationCapacity = 5
            });

            db.SetBuilding(BuildingType.LumberCamp, new BuildingStats
            {
                MaxHealth = Fix64.FromInt(400), VisionRange = Fix64.FromInt(10),
                FootprintHalf = 1, BuildTicks = 300,
                CostWood = 60, IsDropOff = true
            });

            db.SetBuilding(BuildingType.FishingWharf, new BuildingStats
            {
                MaxHealth = Fix64.FromInt(400), VisionRange = Fix64.FromInt(10),
                FootprintHalf = 1, BuildTicks = 400,
                CostWood = 70, RequiresWaterAdjacency = true, IsDropOff = true
            });

            db.SetBuilding(BuildingType.Dock, new BuildingStats
            {
                MaxHealth = Fix64.FromInt(600), VisionRange = Fix64.FromInt(15),
                FootprintHalf = 2, BuildTicks = 500,
                CostWood = 100, CostStone = 50,
                RequiresWaterAdjacency = true,
                TrainableMask = TrainMask(EntityKind.Ship)
            });

            db.SetNode(ResourceNodeType.Forest, new NodeStats { Capacity = 300, Yields = ResourceType.Wood });
            db.SetNode(ResourceNodeType.FishShoal, new NodeStats { Capacity = 400, Yields = ResourceType.Food });
            db.SetNode(ResourceNodeType.StoneOutcrop, new NodeStats { Capacity = 250, Yields = ResourceType.Stone });

            return db;
        }
    }
}
